spring:
  application:
    name: PayTogether

  datasource:
    url: jdbc:h2:mem:paytogetherdb;
    driver-class-name: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      enabled: true

  flyway:
    enabled: true
    locations: classpath:db/migration

logging:
  level:
    org:
      springframework:
        jdbc:
          core: DEBUG
          datasource: DEBUG
          core.StatementCreatorUtils: TRACE
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
      flywaydb:
        core: DEBUG